import Database from "better-sqlite3";
import { randomUUID } from "node:crypto";
import { existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { citationSchema, enforceSyncSafety, extractionCacheKey, fileClaimSchema, fileEvidenceSchema, profileSchema, sha256, sourceSchema, type Citation, type FileClaim, type FileEvidence, type ProjectProfile, type Source } from "@mobile-spec-brain/core";

const directoryName = ".spec-brain";
export function specBrainDirectory(projectRoot: string): string { return join(projectRoot, directoryName); }
function normalize(value: unknown): unknown { if (Array.isArray(value)) return value.map(normalize); if (value !== null && typeof value === "object") return Object.fromEntries(Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, nested]) => [key, normalize(nested)])); return value; }
export function stableJson(value: unknown): string { return `${JSON.stringify(normalize(value), null, 2)}\n`; }
function writeAtomic(path: string, value: unknown): void { mkdirSync(dirname(path), { recursive: true }); const temporary = `${path}.${randomUUID()}.tmp`; writeFileSync(temporary, stableJson(value)); renameSync(temporary, path); }
function readJson(path: string): unknown { return JSON.parse(readFileSync(path, "utf8")); }
function jsonFiles(directory: string): string[] { return existsSync(directory) ? readdirSync(directory, { withFileTypes: true }).flatMap((entry) => entry.isDirectory() ? jsonFiles(join(directory, entry.name)) : entry.name.endsWith(".json") ? [join(directory, entry.name)] : []) : []; }
function sourceMap(root: string): Map<string, Source> { return new Map(((readJson(join(root, "sources.json")) as unknown[]).map((item) => sourceSchema.parse(item))).map((source) => [source.id, source])); }
function sourceDirectory(brainRoot: string, source: Source): string { return isAbsolute(source.root) ? source.root : resolve(brainRoot, source.root); }

export function initializeFileStore(projectRoot: string): string {
  const root = specBrainDirectory(projectRoot); for (const path of ["evidence", "claims", "events", "extractions", "spec", ".index"]) mkdirSync(join(root, path), { recursive: true });
  if (!existsSync(join(root, "sources.json"))) writeAtomic(join(root, "sources.json"), []);
  if (!existsSync(join(root, "concepts.json"))) writeAtomic(join(root, "concepts.json"), []);
  if (!existsSync(join(root, "profile.json"))) writeAtomic(join(root, "profile.json"), { status: "PROPOSED", entries: [], updatedAt: new Date().toISOString() });
  return root;
}
export function appendFileEvent(root: string, actor: string, operation: string, payload: unknown): string { const occurredAt = new Date().toISOString(); const id = `${occurredAt.replace(/[:.]/g, "-")}-${randomUUID()}`; writeAtomic(join(root, "events", `${id}.json`), { actor, id, occurredAt, operation, payload }); return id; }
export function readProfile(root: string): ProjectProfile { return profileSchema.parse(readJson(join(root, "profile.json"))); }

function citedContent(root: string, candidate: Citation): { content?: string; reason?: "ORPHANED" } {
  const citation = citationSchema.parse(candidate); const source = sourceMap(root).get(citation.sourceId); if (!source) return { reason: "ORPHANED" };
  const sourceRoot = resolve(sourceDirectory(root, source)); const target = resolve(sourceRoot, citation.path);
  if (target !== sourceRoot && !target.startsWith(`${sourceRoot}/`)) throw new Error("Citation path escapes its source root.");
  if (!existsSync(target)) return { reason: "ORPHANED" };
  const lines = readFileSync(target, "utf8").split("\n"); if (citation.range[1] > lines.length) throw new Error(`Citation range ${citation.range.join("-")} is outside ${citation.path}.`);
  return { content: lines.slice(citation.range[0] - 1, citation.range[1]).join("\n") };
}
export function validateCitation(root: string, citation: Citation): void { const cited = citedContent(root, citation); if (!cited.content) throw new Error(`Citation cannot be verified: ${cited.reason}.`); const actual = `sha256:${sha256(cited.content)}`; if (actual !== citation.contentHash) throw new Error(`Citation content hash mismatch. Expected ${citation.contentHash}, actual ${actual}; cited content: ${JSON.stringify(cited.content)}.`); }
export function proposeProfile(root: string, profile: Omit<ProjectProfile, "status" | "updatedAt">, actor: string): ProjectProfile { for (const entry of profile.entries) for (const citation of entry.citations) validateCitation(root, citation); const next = profileSchema.parse({ ...profile, status: "PROPOSED", updatedAt: new Date().toISOString() }); writeAtomic(join(root, "profile.json"), next); appendFileEvent(root, actor, "profile.propose", { entries: next.entries.length }); return next; }
export interface EvidenceRecordInput { citation: Citation; kind: string; observation: Record<string, unknown>; extractor: { id: string; version: string; model?: string; promptVersion?: string; cacheKey?: string }; confidence: number; authority: number; }
export function recordEvidence(root: string, input: EvidenceRecordInput, actor: string): FileEvidence { if (readProfile(root).status !== "APPROVED") throw new Error("Profile must be APPROVED before recording evidence."); validateCitation(root, input.citation); const id = `ev_${sha256(stableJson(input.citation))}`; const record = fileEvidenceSchema.parse({ id, ...input, state: "ACTIVE", recordedAt: new Date().toISOString() }); const path = join(root, "evidence", id.slice(3, 5), `${id}.json`); if (!existsSync(path)) { writeAtomic(path, record); const concepts = readJson(join(root, "concepts.json")) as unknown[]; if (!concepts.some((value) => (value as { name?: string }).name === input.kind)) writeAtomic(join(root, "concepts.json"), [...concepts, { kind: "DISCOVERED_CONCEPT", name: input.kind }]); appendFileEvent(root, actor, "evidence.record", { id }); } return fileEvidenceSchema.parse(readJson(path)); }
function filesUnder(path: string): string[] { if (!existsSync(path)) return []; const stat = statSync(path); return stat.isDirectory() ? readdirSync(path).sort().flatMap((name) => filesUnder(join(path, name))) : [path]; }
function scopeContentHash(root: string, scope: string): string { const source = sourceMap(root).get("project"); if (!source) return sha256(scope); const sourceRoot = sourceDirectory(root, source); const target = resolve(sourceRoot, scope); if (target !== sourceRoot && !target.startsWith(`${resolve(sourceRoot)}/`)) throw new Error("Extraction scope escapes its source root."); const files = filesUnder(target); return files.length ? sha256(stableJson(files.map((file) => ({ path: relative(sourceRoot, file), hash: sha256(readFileSync(file, "utf8")) })))) : sha256(scope); }
export interface ExtractionProposal { extractor: { id: string; version: string; model?: string; promptVersion?: string }; observations: EvidenceRecordInput[]; }
export function extractEvidence(root: string, scope: string, proposal: ExtractionProposal, actor: string): { cacheKey: string; reused: boolean; evidence: FileEvidence[] } {
  if (readProfile(root).status !== "APPROVED") throw new Error("Profile must be APPROVED before extraction.");
  enforceSyncSafety({ changedEntities: proposal.observations.length, knownEntities: Math.max(evidenceRecords(root).length, 1), invalidatedClaims: 0 }, { maxSourceChangeRatio: 50, maxClaimInvalidation: 500 });
  const cacheKey = extractionCacheKey({ contentHash: scopeContentHash(root, scope), extractorId: proposal.extractor.id, extractorVersion: proposal.extractor.version, promptVersion: proposal.extractor.promptVersion ?? "unspecified", modelVersion: proposal.extractor.model ?? "unspecified", schemaVersion: "file-protocol-v1" }); const cachePath = join(root, "extractions", `${cacheKey}.json`);
  if (existsSync(cachePath)) { const cached = readJson(cachePath) as { evidenceIds: string[] }; const index = new Map(evidenceRecords(root).map((item) => [item.id, item])); return { cacheKey, reused: true, evidence: cached.evidenceIds.map((id) => index.get(id)).filter((item): item is FileEvidence => item !== undefined) }; }
  const evidence = proposal.observations.map((input) => recordEvidence(root, { ...input, extractor: { ...input.extractor, ...proposal.extractor, cacheKey } }, actor)); writeAtomic(cachePath, { cacheKey, evidenceIds: evidence.map((item) => item.id).sort(), extractor: proposal.extractor, scope }); appendFileEvent(root, actor, "extract", { cacheKey, scope, evidenceIds: evidence.map((item) => item.id) }); return { cacheKey, reused: false, evidence };
}
export function evidenceRecords(root: string, query: { kind?: string; path?: string; state?: string; feature?: string } = {}): FileEvidence[] { const featureIds = query.feature ? new Set(claimRecords(root).filter((claim) => claim.feature === query.feature).flatMap((claim) => claim.evidenceIds)) : undefined; return jsonFiles(join(root, "evidence")).map((path) => fileEvidenceSchema.parse(readJson(path))).filter((item) => (!query.kind || item.kind === query.kind) && (!query.path || item.citation.path.includes(query.path)) && (!query.state || item.state === query.state) && (!featureIds || featureIds.has(item.id))).sort((a, b) => a.id.localeCompare(b.id)); }
export function claimRecords(root: string): FileClaim[] { return jsonFiles(join(root, "claims")).map((path) => fileClaimSchema.parse(readJson(path))).sort((a, b) => a.id.localeCompare(b.id)); }
function claimPath(root: string, claim: FileClaim): string { return join(root, "claims", claim.feature, `${claim.id}.json`); }
export function writeClaim(root: string, claim: FileClaim, actor: string, operation: "claim.propose" | "claim.supersede" = "claim.propose"): FileClaim { const evidence = new Set(evidenceRecords(root).map((item) => item.id)); if (!claim.evidenceIds.every((id) => evidence.has(id))) throw new Error("Claim references evidence that does not exist."); const parsed = fileClaimSchema.parse(claim); if (existsSync(claimPath(root, parsed))) throw new Error("Claims are immutable; create a new claim and supersede the prior record."); if (operation === "claim.supersede") { if (!parsed.supersedes) throw new Error("Superseding claim must declare supersedes."); const prior = claimRecords(root).find((item) => item.id === parsed.supersedes); if (!prior) throw new Error("Claim to supersede does not exist."); writeAtomic(claimPath(root, prior), { ...prior, state: "SUPERSEDED" }); }
  writeAtomic(claimPath(root, parsed), parsed); appendFileEvent(root, actor, operation, { id: parsed.id, supersedes: parsed.supersedes }); return parsed; }
export function invalidateEvidence(root: string, evidenceId: string, actor: string): FileEvidence { if (actor !== "human") throw new Error("Only a human actor may invalidate evidence."); const evidence = evidenceRecords(root).find((item) => item.id === evidenceId); if (!evidence) throw new Error("Evidence does not exist."); const next = { ...evidence, state: "INVALIDATED" as const }; writeAtomic(join(root, "evidence", evidence.id.slice(3, 5), `${evidence.id}.json`), next); appendFileEvent(root, actor, "evidence.invalidate", { id: evidenceId }); return next; }
export function verifyFileStore(root: string, actor: string): { stale: string[]; orphaned: string[]; claimsNeedingReview: string[] } { const stale: string[] = []; const orphaned: string[] = []; for (const evidence of evidenceRecords(root)) { if (evidence.state === "INVALIDATED") continue; const cited = citedContent(root, evidence.citation); const state = !cited.content ? "ORPHANED" : `sha256:${sha256(cited.content)}` === evidence.citation.contentHash ? "ACTIVE" : "STALE"; if (state !== evidence.state) writeAtomic(join(root, "evidence", evidence.id.slice(3, 5), `${evidence.id}.json`), { ...evidence, state }); if (state === "STALE") stale.push(evidence.id); if (state === "ORPHANED") orphaned.push(evidence.id); }
  const invalid = new Set(evidenceRecords(root).filter((item) => item.state !== "ACTIVE").map((item) => item.id)); const claimsNeedingReview: string[] = []; for (const claim of claimRecords(root)) if (claim.state === "ACTIVE" && claim.evidenceIds.some((id) => invalid.has(id))) { writeAtomic(claimPath(root, claim), { ...claim, state: "NEEDS_REVIEW" }); claimsNeedingReview.push(claim.id); } appendFileEvent(root, actor, "verify", { claimsNeedingReview, orphaned, stale }); return { stale, orphaned, claimsNeedingReview }; }
export function reindexFileStore(root: string): { evidence: number; claims: number } { const index = join(root, ".index"); rmSync(index, { recursive: true, force: true }); mkdirSync(index, { recursive: true }); const database = new Database(join(index, "workspace.sqlite")); database.exec("CREATE TABLE evidence (id TEXT PRIMARY KEY, state TEXT NOT NULL); CREATE TABLE claims (id TEXT PRIMARY KEY, feature TEXT NOT NULL, predicate TEXT NOT NULL, state TEXT NOT NULL);"); const evidence = evidenceRecords(root); const claims = claimRecords(root); for (const item of evidence) database.prepare("INSERT INTO evidence VALUES (?, ?)").run(item.id, item.state); for (const item of claims) database.prepare("INSERT INTO claims VALUES (?, ?, ?, ?)").run(item.id, item.feature, item.predicate, item.state); database.close(); return { evidence: evidence.length, claims: claims.length }; }
export function graphQuery(root: string, query: { feature?: string; predicate?: string; state?: string }): { claims: FileClaim[]; evidence: FileEvidence[] } { const claims = claimRecords(root).filter((item) => (!query.feature || item.feature === query.feature) && (!query.predicate || item.predicate === query.predicate) && (!query.state || item.state === query.state)); const ids = new Set(claims.flatMap((item) => item.evidenceIds)); return { claims, evidence: evidenceRecords(root).filter((item) => ids.has(item.id)) }; }
export function coverage(root: string): unknown { const evidence = evidenceRecords(root); const claims = claimRecords(root); return { sources: sourceMap(root).size, evidence: { total: evidence.length, active: evidence.filter((item) => item.state === "ACTIVE").length, stale: evidence.filter((item) => item.state === "STALE").length, orphaned: evidence.filter((item) => item.state === "ORPHANED").length }, claims: { total: claims.length, needsReview: claims.filter((item) => item.state === "NEEDS_REVIEW").length } }; }
export function projectSource(root: string, projectRoot: string): Source { return { id: "project", root: relative(root, projectRoot) || ".", type: "LOCAL" }; }
