import { z } from "zod";
import { sha256 } from "./hash.js";
import type { FileClaim, FileEvidence } from "./file-protocol.js";

const evidenceIds = z.array(z.string()).default([]); const unknown = z.object({ field: z.string(), reason: z.string(), evidenceIds });
const api = z.object({ method: z.string(), path: z.string(), parameters: z.array(z.unknown()), requestBody: z.unknown(), responses: z.record(z.unknown()), evidenceIds, state: z.string() });
export const fileSpecSchema = z.object({ version: z.literal(1), graphHash: z.string().length(64), feature: z.object({ key: z.string(), displayName: z.string(), evidenceIds }), completeness: z.object({ knownFields: z.number(), unknownFields: z.number(), staleFields: z.number(), ratio: z.number() }), figmaFrames: z.array(z.object({ nodeId: z.string(), name: z.string(), evidenceIds, state: z.string() })), api: z.array(api), implementations: z.array(z.object({ platform: z.string(), status: z.string(), location: z.string().optional(), evidenceIds, state: z.string() })), navigation: z.object({ incoming: z.array(z.object({ route: z.string(), platform: z.string().optional(), evidenceIds, state: z.string() })), outgoing: z.array(z.object({ route: z.string(), platform: z.string().optional(), evidenceIds, state: z.string() })) }), claims: z.array(z.unknown()), evidence: z.array(z.unknown()), unknowns: z.array(unknown) });
export type FileSpec = z.infer<typeof fileSpecSchema>;
const record = (value: unknown): Record<string, unknown> => value !== null && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
export function buildFileSpec(feature: string, claims: FileClaim[], evidence: FileEvidence[]): FileSpec {
  const evidenceState = new Map(evidence.map((item) => [item.id, item.state])); const state = (claim: FileClaim) => claim.state !== "ACTIVE" || claim.evidenceIds.some((id) => evidenceState.get(id) !== "ACTIVE") ? "NEEDS_REVIEW" : "ACTIVE"; const ids = (claim: FileClaim) => claim.evidenceIds;
  const apiContracts = claims.map((claim) => ({ claim, object: record(claim.object) })).filter(({ object }) => typeof object.method === "string" && typeof object.path === "string").map(({ claim, object }) => ({ method: object.method as string, path: object.path as string, parameters: Array.isArray(object.parameters) ? object.parameters : [], requestBody: object.requestBody ?? { status: "UNKNOWN", reason: "REQUEST_BODY_NOT_DECLARED" }, responses: record(object.responses), evidenceIds: ids(claim), state: state(claim) }));
  const figmaFrames = claims.map((claim) => ({ claim, object: record(claim.object) })).filter(({ object }) => typeof object.nodeId === "string" && typeof object.name === "string").map(({ claim, object }) => ({ nodeId: object.nodeId as string, name: object.name as string, evidenceIds: ids(claim), state: state(claim) }));
  const implementations = claims.map((claim) => ({ claim, object: record(claim.object) })).filter(({ object }) => typeof object.platform === "string" && typeof object.status === "string").map(({ claim, object }) => ({ platform: object.platform as string, status: object.status as string, location: typeof object.location === "string" ? object.location : undefined, evidenceIds: ids(claim), state: state(claim) }));
  const nav = (direction: string) => claims.map((claim) => ({ claim, object: record(claim.object) })).filter(({ object }) => object.direction === direction && typeof object.route === "string").map(({ claim, object }) => ({ route: object.route as string, platform: typeof object.platform === "string" ? object.platform : undefined, evidenceIds: ids(claim), state: state(claim) }));
  const display = claims.map((claim) => record(claim.object).displayName).find((value): value is string => typeof value === "string") ?? feature;
  const unknowns = claims.length === 0 ? [{ field: "claims", reason: "EVIDENCE_ABSENT", evidenceIds: [] }] : claims.filter((claim) => state(claim) !== "ACTIVE").map((claim) => ({ field: claim.id, reason: claim.state, evidenceIds: claim.evidenceIds })); const all = claims.length + unknowns.length; const active = claims.filter((claim) => state(claim) === "ACTIVE").length;
  return fileSpecSchema.parse({ version: 1, graphHash: sha256(JSON.stringify({ claims, evidence })), feature: { key: feature, displayName: display, evidenceIds: [...new Set(claims.flatMap(ids))].sort() }, completeness: { knownFields: active, unknownFields: all - active, staleFields: claims.filter((claim) => claim.evidenceIds.some((id) => evidenceState.get(id) !== "ACTIVE")).length, ratio: all === 0 ? 0 : active / all }, figmaFrames, api: apiContracts, implementations, navigation: { incoming: nav("incoming"), outgoing: nav("outgoing") }, claims, evidence, unknowns });
}
