import { readFileSync } from "node:fs";

export interface ApiParameter { name: string; location: "path" | "query" | "header"; required: boolean; schema: unknown; }
export interface ApiResponse { description?: string; schema: unknown; }
export interface OpenApiOperation { method: string; path: string; normalizedPath: string; operationId?: string; summary?: string; description?: string; tags: string[]; deprecated: boolean; parameters: ApiParameter[]; requestBody: unknown; responses: Record<string, ApiResponse>; }
type RecordValue = Record<string, unknown>; const methods = new Set(["get", "put", "post", "delete", "patch", "head", "options"]);
const record = (value: unknown): RecordValue => value !== null && typeof value === "object" && !Array.isArray(value) ? value as RecordValue : {};
const list = (value: unknown): unknown[] => Array.isArray(value) ? value : [];
export function normalizeOpenApiPath(path: string): string { return path.replace(/\{[^}]+\}/g, "{0}"); }
function resolveReferences(value: unknown, root: RecordValue, stack: string[] = []): unknown { if (Array.isArray(value)) return value.map((item) => resolveReferences(item, root, stack)); const valueRecord = record(value); if (!Object.keys(valueRecord).length) return value; if (typeof valueRecord.$ref === "string") { const reference = valueRecord.$ref; if (!reference.startsWith("#/")) return { status: "UNKNOWN", reason: "UNRESOLVABLE_REF", ref: reference }; if (stack.includes(reference)) return { status: "UNKNOWN", reason: "CIRCULAR_REF", ref: reference }; const target = reference.slice(2).split("/").reduce<unknown>((current, key) => record(current)[key], root); return target === undefined ? { status: "UNKNOWN", reason: "UNRESOLVABLE_REF", ref: reference } : resolveReferences(target, root, [...stack, reference]); } return Object.fromEntries(Object.entries(valueRecord).sort(([a], [b]) => a.localeCompare(b)).map(([key, nested]) => [key, resolveReferences(nested, root, stack)])); }
function contentSchema(content: unknown, root: RecordValue): unknown { const media = record(record(content)["application/json"]); return media.schema === undefined ? { status: "UNKNOWN", reason: "SCHEMA_NOT_DECLARED" } : resolveReferences(media.schema, root); }
function parameters(pathLevel: unknown, operationLevel: unknown, root: RecordValue): ApiParameter[] { return [...list(pathLevel), ...list(operationLevel)].map((item) => record(resolveReferences(item, root))).filter((item) => item.in === "path" || item.in === "query" || item.in === "header").map((item) => ({ name: typeof item.name === "string" ? item.name : "UNKNOWN", location: item.in as ApiParameter["location"], required: item.required === true, schema: item.schema === undefined ? { status: "UNKNOWN", reason: "SCHEMA_NOT_DECLARED" } : resolveReferences(item.schema, root) })).sort((a, b) => `${a.location}:${a.name}`.localeCompare(`${b.location}:${b.name}`)); }
/** Deterministic machine-format parser; it does not inspect application code. */
export function parseOpenApi(path: string): OpenApiOperation[] { const document = record(JSON.parse(readFileSync(path, "utf8"))); return Object.entries(record(document.paths)).flatMap(([route, rawPathItem]) => { const pathItem = record(rawPathItem); return Object.entries(pathItem).filter(([method]) => methods.has(method.toLowerCase())).map(([method, rawOperation]) => { const operation = record(rawOperation); const responses = Object.fromEntries(Object.entries(record(operation.responses)).sort(([a], [b]) => a.localeCompare(b)).map(([status, rawResponse]) => { const response = record(resolveReferences(rawResponse, document)); return [status, { description: typeof response.description === "string" ? response.description : undefined, schema: contentSchema(response.content, document) }]; })); const request = operation.requestBody === undefined ? { status: "UNKNOWN", reason: "REQUEST_BODY_NOT_DECLARED" } : contentSchema(record(resolveReferences(operation.requestBody, document)).content, document); return { method: method.toUpperCase(), path: route, normalizedPath: normalizeOpenApiPath(route), operationId: typeof operation.operationId === "string" ? operation.operationId : undefined, summary: typeof operation.summary === "string" ? operation.summary : undefined, description: typeof operation.description === "string" ? operation.description : undefined, tags: list(operation.tags).filter((tag): tag is string => typeof tag === "string").sort(), deprecated: operation.deprecated === true, parameters: parameters(pathItem.parameters, operation.parameters, document), requestBody: request, responses }; }); }).sort((a, b) => `${a.method} ${a.path}`.localeCompare(`${b.method} ${b.path}`)); }
