CREATE TABLE IF NOT EXISTS schema_migrations (version TEXT PRIMARY KEY, applied_at TEXT NOT NULL);
CREATE TABLE workspaces (id TEXT PRIMARY KEY, name TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE sources (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id), type TEXT NOT NULL, status TEXT NOT NULL, configuration_json TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE source_entities (id TEXT PRIMARY KEY, source_id TEXT NOT NULL REFERENCES sources(id), external_id TEXT NOT NULL, kind TEXT NOT NULL, state TEXT NOT NULL, UNIQUE(source_id, external_id));
CREATE TABLE raw_revisions (id TEXT PRIMARY KEY, source_entity_id TEXT NOT NULL REFERENCES source_entities(id), revision TEXT NOT NULL, content_hash TEXT NOT NULL, content_json TEXT NOT NULL, fetched_at TEXT NOT NULL, source_updated_at TEXT, metadata_json TEXT NOT NULL, UNIQUE(source_entity_id, revision));
CREATE TABLE raw_blocks (id TEXT PRIMARY KEY, raw_revision_id TEXT NOT NULL REFERENCES raw_revisions(id), external_id TEXT NOT NULL, content_hash TEXT NOT NULL, content_json TEXT NOT NULL, metadata_json TEXT NOT NULL, UNIQUE(raw_revision_id, external_id));
CREATE TABLE evidence (id TEXT PRIMARY KEY, raw_block_id TEXT NOT NULL REFERENCES raw_blocks(id), kind TEXT NOT NULL, subject TEXT NOT NULL, predicate TEXT NOT NULL, value_json TEXT NOT NULL, extraction_confidence REAL NOT NULL, authority REAL NOT NULL, provenance_json TEXT NOT NULL, state TEXT NOT NULL);
CREATE TABLE decisions (id TEXT PRIMARY KEY, evidence_id TEXT NOT NULL REFERENCES evidence(id), state TEXT NOT NULL, approved_at TEXT, approved_by TEXT);
CREATE TABLE features (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id), canonical_key TEXT NOT NULL, display_name TEXT NOT NULL, state TEXT NOT NULL, UNIQUE(workspace_id, canonical_key));
CREATE TABLE specs (id TEXT PRIMARY KEY, feature_id TEXT REFERENCES features(id), key TEXT NOT NULL, state TEXT NOT NULL, UNIQUE(feature_id, key));
CREATE TABLE spec_revisions (id TEXT PRIMARY KEY, spec_id TEXT NOT NULL REFERENCES specs(id), value_json TEXT NOT NULL, validity_json TEXT NOT NULL, lifecycle TEXT NOT NULL, confidence REAL NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE edges (id TEXT PRIMARY KEY, from_id TEXT NOT NULL, to_id TEXT NOT NULL, relation TEXT NOT NULL, UNIQUE(from_id, to_id, relation));
CREATE TABLE findings (id TEXT PRIMARY KEY, feature_id TEXT REFERENCES features(id), type TEXT NOT NULL, severity TEXT NOT NULL, state TEXT NOT NULL, explanation_json TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE sync_cursors (source_id TEXT PRIMARY KEY REFERENCES sources(id), cursor TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE extractor_cache (cache_key TEXT PRIMARY KEY, result_json TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE policies (id TEXT PRIMARY KEY, workspace_id TEXT NOT NULL REFERENCES workspaces(id), type TEXT NOT NULL, definition_json TEXT NOT NULL, version TEXT NOT NULL);
CREATE TABLE events (id TEXT PRIMARY KEY, occurred_at TEXT NOT NULL, actor TEXT NOT NULL, operation TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, evidence_ids_json TEXT NOT NULL, reason TEXT NOT NULL, payload_json TEXT NOT NULL);
CREATE INDEX idx_events_entity ON events(entity_id, occurred_at);
CREATE INDEX idx_edges_from ON edges(from_id);
CREATE INDEX idx_evidence_subject ON evidence(subject);
