#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { buildSourceSpec, renderSourceSpecMarkdown } from "@mobile-spec-brain/core";
import { appendFileEvent, claimRecords, coverage, evidenceRecords, initializeFileStore, proposeProfile, readProfile, recordEvidence, reindexFileStore, specBrainDirectory, verifyFileStore, writeClaim } from "@mobile-spec-brain/storage";

const projectRoot = process.cwd();
const root = specBrainDirectory(projectRoot);
const json = process.argv.includes("--json");
const [command, subcommand, ...args] = process.argv.slice(2).filter((arg) => arg !== "--json");
function output(value: unknown): void { console.log(JSON.stringify(value, null, 2)); }
function requireStore(): boolean { if (existsSync(root)) return true; output({ status: "error", code: "SPEC_BRAIN_NOT_INITIALIZED", message: "Run `spec-brain init` first." }); process.exitCode = 2; return false; }
function fileArgument(): string | undefined { const index = args.indexOf("--file"); return index >= 0 ? args[index + 1] : undefined; }

function init(): void { initializeFileStore(projectRoot); const sources = join(root, "sources.json"); if (JSON.parse(readFileSync(sources, "utf8")).length === 0) writeFileSync(sources, JSON.stringify([{ id: "project", root: projectRoot, type: "LOCAL" }], null, 2) + "\n"); output({ status: "initialized", root }); }
function profile(): void { if (!requireStore()) return; if (subcommand === "read") { output({ status: "complete", profile: readProfile(root) }); return; } if (subcommand === "propose") { const path = fileArgument(); if (!path) throw new Error("Use `spec-brain profile propose --file profile.json`."); output({ status: "proposed", profile: proposeProfile(root, JSON.parse(readFileSync(resolve(projectRoot, path), "utf8")), "agent") }); return; } throw new Error("Use `spec-brain profile read|propose`."); }
function evidence(): void { if (!requireStore()) return; if (subcommand === "query") { output({ status: "complete", evidence: evidenceRecords(root) }); return; } if (subcommand !== "record") throw new Error("Use `spec-brain evidence record|query`."); const path = fileArgument(); if (!path) throw new Error("Use `spec-brain evidence record --file evidence.json`."); output({ status: "recorded", evidence: recordEvidence(root, JSON.parse(readFileSync(resolve(projectRoot, path), "utf8")), "agent") }); }
function claim(): void { if (!requireStore()) return; if (subcommand !== "propose" && subcommand !== "supersede") throw new Error("Use `spec-brain claim propose|supersede --file claim.json`."); const path = fileArgument(); if (!path) throw new Error("Use `spec-brain claim ${subcommand} --file claim.json`."); const claim = JSON.parse(readFileSync(resolve(projectRoot, path), "utf8")); output({ status: "recorded", claim: writeClaim(root, claim, "agent") }); }
function spec(): void { if (!requireStore()) return; if (subcommand !== "render") throw new Error("Use `spec-brain spec render <feature>`. "); const feature = args.find((arg) => !arg.startsWith("--")); if (!feature) throw new Error("Feature is required."); const claims = claimRecords(root).filter((item) => item.feature === feature); const evidenceIds = [...new Set(claims.flatMap((item) => item.evidenceIds))]; if (evidenceIds.length === 0) { output({ status: "complete", feature, unknown: "EVIDENCE_ABSENT" }); return; } const data = buildSourceSpec({ feature: { key: feature, displayName: feature, evidenceIds }, figmaFrames: [], api: [], navigation: { incoming: [], outgoing: [] }, unknowns: [{ field: "api", reason: "EVIDENCE_ABSENT", evidenceIds: [] }, { field: "navigation", reason: "EVIDENCE_ABSENT", evidenceIds: [] }], graphState: { claims } }); const directory = join(root, "spec"); mkdirSync(directory, { recursive: true }); writeFileSync(join(directory, `${feature}.spec.json`), JSON.stringify(data, null, 2) + "\n"); writeFileSync(join(directory, `${feature}.md`), renderSourceSpecMarkdown(data)); output({ status: "rendered", feature, graphHash: data.graphHash }); }

try { if (command === "init") init(); else if (command === "profile") profile(); else if (command === "evidence") evidence(); else if (command === "claim") claim(); else if (command === "verify") { if (requireStore()) output({ status: "complete", ...verifyFileStore(root, "verifier") }); } else if (command === "reindex") { if (requireStore()) output({ status: "complete", ...reindexFileStore(root) }); } else if (command === "coverage") { if (requireStore()) output({ status: "complete", coverage: coverage(root) }); } else if (command === "spec") spec(); else { console.log("Usage: spec-brain <init|profile|evidence|claim|verify|reindex|coverage|spec> [--json]"); process.exitCode = 2; } } catch (error) { output({ status: "error", message: error instanceof Error ? error.message : String(error) }); process.exitCode = 2; }
